- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - varaibles.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: please enter your name
  #   private: false
  # - name: WISHES
  #   prompt: please enter yout wishes
  #   private: false
  vars:
    PERSON: "Siva from PLAY"
    WISHES: "Morning from PLAY"
  tasks:
  - name: check variables
    # vars:
    #   PERSON: "Siva from TASK"
    #   WISHES: "Morning from TASK"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, GOOD {{WISHES}}"